<<<<<<< HEAD
spring.application.name=demo
=======
spring.application.name=Trab-ArquiteturaDeSoftware
# Configurações básicas do H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Criar e atualizar o schema automaticamente
spring.jpa.hibernate.ddl-auto=update

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
>>>>>>> 1e34944342792722da8d5f6be7370aeaa2a75c49
